<?php 
 return array (
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_name' => 'thinkphp_system',
  'db_user' => 'root',
  'db_pwd' => 'root',
  'db_port' => 3306,
  'db_prefix' => 'tp_',
  'SMTP_SERVER' => 'smtp.163.com',
  'SMTP_PORT' => 25,
  'SMTP_USER_EMAIL' => '4u4v@163.com',
  'SMTP_USER' => '4u4v@163.com',
  'SMTP_PWD' => '15083523531',
  'SMTP_MAIL_TYPE' => 'HTML',
  'SMTP_TIME_OUT' => 60,
  'SMTP_AUTH' => 1,
  'web_name' => 'CMS网站后台管理系统',
  'web_url' => 'http://localhost/ThinkPHP_Backend_System/',
  'web_path' => '/',
  'web_icp' => '闽ICP备12345678号',
  'CRON_MAX_TIME' => 60,
  'web_copyright' => 'Copyright © <a href="http://studio.js.cn" target="_blank">水木工作室</a> 版权所有',
  'web_tongji' => '',
  'web_admin_pagenum' => 20,
  'web_home_pagenum' => 15,
  'web_adsensepath' => 'Public/Banner',
  'DB_BACKUP' => 'admin/backup',
); 
 ?>
